#define LIB_SAPI "libsapi.so.0"
#define LIB_TCTI_SOCKET_LEGACY "libtcti-socket.so.0"
#define LIB_TCTI_TABRMD "libtss2-tcti-tabrmd.so.0" 
#define LIB_TCTI_TABRMD_LEGACY "libtcti-tabrmd.so.0"
#define LIB_TCTI_MSSIM "libtss2-tcti-mssim.so.0"
#define LIB_TSS2_SYS "libtss2-sys.so.0"
#define LIB_TSS2_MU "libtss2-mu.so.0"
#define LIB_TSPI "libtspi.so.1"

#include "tpm12.h"
#include "tpm20.h"